<?php

namespace App\DataFixtures;

class TheaterProvider
{
    private $styles = [
        "Boulevard",
        "Art du récit",
        "Café-théâtre",
        "Chanson",
        "Cirque",
        "Classique",
        "Clown",
        "Comédie",
        "Concert",
        "Conférence-spectacle",
        "Conte",
        "Contemporain",
        "Danse",
        "Danse-théâtre",
        "Drame",
        "Humour",
        "Improvisation",
        "Lecture",
        "Magie",
        "Marionnette-objet",
        "Mime",
        "Performance",
        "Pluridisciplinaire",
        "Poésie",
        "Policier",
        "Spectacle musical",
        "Théâtre",
        "Théâtre citoyen",
        "Théâtre masqué",
        "Théâtre musical",
    ];

    private $titles = [
        "Chérie c’est qui le patron",
        "Choisir de vivre",
        "Chris 120kg d’humour “c’est pas moi c’est eux!”",
        "Chroniques d’un escargot",
        "Chut... mes lunettes ont un secret !",
        "Chuuut ! Lectures bruitées # Opus 2",
        "Ciel ! Mon zizi !",
        "ClassiSwing’: concert des 10 ans",
        "Claudel",
        "Colères",
        "Colocs et plus si complicité",
        "Com’ et dit... et non dit",
        "Combat de nègre et de chiens",
        "Combat de Pauvres",
        "Comédie sur un quai de gare",
        "Comédiens !",
        "Comme à la maison",
        "Comme disait mon père",
        "Comme un trio, d’après ",
        "Tristesse",
        "Comment ça va ?",
        "Comment épouser un milliardaire",
        "Comment Virginie D. a sauvé ma vie..",
        "Concert à table",
        "Concert Louise O’sman",
        "Confessions nocturnes",
        "Confiance, ôde à la terre",
        "Confidanse",
        "Conseils à des jeunes qui veulent rire de tout",
        "Contes à la Perrault",
        "Contes Coquin",
        "Copains pour toujours... ou presque !",
        "Costa le Rouge",
        "Cougar Débutant",
        "Couleurs Cuivres #3",
        "Coup de foudre à Casteljarnac",
        "Courtisanes",
        "Crâne",
        "Cri de mes racines",
        "Crocodile",
        "Curé le jour, athée la nuit...",
        "Cyrano",
        "Cyrano de Bergerac",
        "Cyrano(s)",
        "Danny and the Deep Blue Sea",
        "Dans cet Amour, Nous eû",
        "Orages...",
        "Dans l’ombre de Peter Pan",
        "Dans la bouche",
        "Dans ma tête d’Alouette",
        "Dans son monde",
        "David Voinson",
        "De A à Zef",
        "De l’Air !",
        "De quoi je me mêle !",
        "Débris",
        "Déchets et des hommes - la face déchets ducapitalisme",
        "Déglutis, ça ira mieux",
        "Délire à deux",
        "Demain, je me marie !",
        "Démodés",
        "Denise dans IncontrÔlable!",
        "Denise Jardinière vous invite chez elle",
        "Dernière fête",
        "Des air(e)s d’anges",
        "Des caravelles & des batailles",
        "Des gens qui dansent (petite histoire)",
        "Quantités négligeables",
        "Des Lustre",
        "Des plans sur la comète",
        "Désaxé",
        "Désintégration",
        "Désobéir - Pièce d’actualité n°9 p. 3",
        "Désormais si proches",
        "Desperate mamies return",
        "Deux femmes pour un fantôme",
        "Deux mètres, et davantage de liberté",
        "Deux rien",
        "Diaba l’ange tirailleur",
        "Dictateur, mais pas trop",
        "Diktat",
        "Ding Dong !",
        "Diogène ou le sanglot hilar",
        "mouette",
        "Discours d’investiture de la présidence",
        "états-unis",
        "Disparu",
        "Dom Juan",
        "Don Quichotte et Sancho Panza (l’attente del’amante absente)",
        "Dormez je le veux !... ou pas",
        "Dormez, je le veux !",
        "Du bruit (et de fureur",
        "Du fond des âges, chants",
        "d’orient",
        "Du jeu au je",
        "Duo Juan",
        "È un attimo",
        "Eau chaude à tous les étages",
        "Échos ruraux",
        "Éclipse",
        "Ecole des femmes",
        "Eddy Piouc",
        "Ef_femininity",
        "Ego-système, le musée",
        "existenc",
        "Eh bien dansez maintenant",
        "Eh oh les poubelles !",
        "El Gring",
        "El maletazzo - Le coup de la valise",
        "Élevée en plein air",
        "Elle gagne sa vie en volant",
        "Elle’",
        "Ellipse",
        "Eloge du noi",
        "Embarquement Immédiat - Vol TS 236",
        "Emilie Du Châtelet et Voltaire avant Beauvoiret Sartre",
        "Emisfero",
        "Emmy fait son Magic Show",
        "En ce temps là, l’amour..",
        "En panne",
        "En plein air",
        "En réalités",
        "Endormis sous le ciel",
        "enjoy yourself",
        "Ensemble Pas Ensemble",
        "Entends-moi",
        "Entre-sorts",
        "Entre-sorts",
        "Entrelacs p. 3",
        "Envers",
        "Ersatz",
        "Escale",
        "Escargot",
        "Et après",
        "Et Dieu créa... la voix",
        "Et le cœur fume encor",
        "Et si c’était cette nuit..",
        "Et toi, t’es là pour quoi ?",
        "Être là",
        "Europa (Esperanza)",
        "Ex centriques",
        "Exil pour 2 violons",
        "Exit",
        "Exodus",
        "Extases",
        "Fabienne Carat - L’amour est ",
        "prêt p. 1",
        "Fables à tiroirs",
        "Face de Lune",
        "Fahb “en attendant...”",
        "Faire semblant d’être normaux",
        "Fais pas ci, fais pas chat !",
        "Fake New",
        "Farid Chamekh",
        "Fatras",
        "Faut-il tout dire dans son couple?",
        "Fearless",
        "Femme sauvée par un tableau",
        "Femmes",
        "Feu la mère de Madame & Léonie",
        "avance",
        "Fifi",
        "Final Cut",
        "Firmin et Hecto",
        "Flavien, One man show expérimental",
        "Flèche de cœur",
        "Fool for love",
        "For Eve",
        "Formes Brèves",
        "Forward / Into Outside",
        "Fourberie",
        "Foyer",
        "Fragments d’une traversée",
        "Funérarium",
        "Fushigi !",
        "Gaby, mon amour ! La naissance du MusicHal",
        "Gadoue",
        "Gaïa p. 3",
        "Galilée, le mécano",
        "Game of points - 12 points capitaux",
        "Garance [Bleu",
        "Garde alternée mais de nuit",
        "Gatica Embrassons-nous",
        "Genoma B",
        "George Dandin chez Molière en 1668",
        "George et Sarah",
        "George Sand, une femme libre",
        "Georges Dandin zagla",
        "GilgaClash",
        "Gilles Detroit... Pour rire !",
        "Giorda vous hypnotise",
        "Globe Stor",
        "Good nigh",
        "Goodbye Wall Street",
        "Gouâl (chantier en cours)",
        "Govrache “des murmures et des cris",
        "Grou !",
        "Guappecarto",
        "Güe, enfance d’humanité",
        "Guerre, et si ça nous arrivait?",
        "Guillaume, Jean-Luc, Laurent et lajournaliste.",
        "“H.o.m.e.”",
        "Halal Cacher Blues",
        "Hamle",
        "Hands up",
        "Hang Solo en Nocturne",
        "Happy Mâle",
        "Harissa, histoires piquantes et liberté",
        "Tunisie",
        "Hassan de Monaco",
        "Héloise et Tristan",
        "Hen",
        "Hercule à la plage",
        "Hernani ! Brigand de la pensée",
        "Héroïne(s)#2 Des cercles bleus et noirs",
        "Heureusement qu’on ne meurt pasd’amour",
        "Hippolyte",
        "Histoire de l’imposture",
        "Histoire du communisme",
        "malades mentaux",
        "Histoires comme ça",
        "Hommage à G. Brassens : “Il suffit de pousserla porte”",
        "Hors Piste",
        "Hot-House",
        "Hugo, celui du combat ",
        "Huis Clos",
        "Humiliés & Offensés",
        "Hurt me tender",
        "Hypnofolies",
        "Hypnose, et si c’était vous ?",
        "I am the cosmos",
        "I Fratelli Lehman",
        "I Swallowed a Moon Made of Iron p. 2",
        "I.P.A - Un soir comme un Autre",
        "I’m Woma",
        "Il était une femme",
        "Il faut qu’une porte soit fermée",
        "Il n’y a pas si longtemps",
        "Ils n’avaient pas prévu qu’on puisse gagner gagner",
        "Imam pas beaucoup",
        "In-Two",
        "Inging",
        "Ingrid Graziani “Du ring à la scéne”",
        "Inoubliable Sarah Bernhardt",
        "Inquiet moi ?",
        "Instagramable et cervelée",
        "Intimes Galaxies (2019)",
        "Intrigues à la cour royale",
        "Iphigénie à Splot",
        "Isador",
        "J.C.",
        "J’ai flashé sur elle ou le sexe",
        "couple",
        "J’ai mangé du Jacques",
        "J’ai pas toujours dansé comme ça",
        "J’ai rencontré Dieu sur Facebook",
        "J’arrive",
        "J’arriverai par l’ascenseur de",
        "(chronique d’un fan de Thiéfaine",
        "J’aurais pu m’appeler Camille",
        "J’aurais tellement aimé",
        "J’habite une blessure sacrée",
        "J’irai danser avec les requins",
        "J’veux du sexe bordel !",
        "Jacob, Jacob",
        "Jalousie en 3 mails",
        "Jambonlaissé",
        "Je crois que je suis magicien",
        "Je danserai pour toi",
        "Je me porte bien",
        "Je ne suis pas narcissique",
        "Je ne suis pas un spectacle",
        "Je pionce donc je suis",
        "Je sais plus où j’habite ! - ou comment arrêté de vouloir être propriétaire",
        "maison.",
        "Je suis Catherine Deneuve",
        "Je suis là",
        "Je viens d’un pays de neige",
        "Jean et Béatrice",
        "Jean-Marc Lovay, un phare ",
        "montagne",
        "Jean-Pierre, Lui, Moi",
        "Jean-Yves, Patrick et Corinne",
        "Jeanne",
        "Jeannot du Maïs",
        "Jef Kino en concert",
        "Jérémy Crausaz ne veut pas grandir",
        "Jeune Public",
        "Jo Brami - Ma Vie à l’Envers",
        "Johnny : Thibaud Choplin rallume le feu",
        "Joie",
        "Jouliks",
        "Jovany & le dernier saltimbanque",
        "Judith, le corps séparé",
        "Julien Santini s’amuse",
        "Juliette Drouet",
        "Jusqu’à ce que la mort nous sépare",
        "K-barock",
        "Kalakuta Drea",
        "Kapoustnik",
        "Karim Duval dans “Y”",
        "Kelka, chansons théâtrale",
        "Kos",
        "Koteba (travail en cours)",
        "L.U.C.A. (Last Universal",
        "Ancestor)",
        "L’Abattage rituel de Gorge Mastromas",
        "L’Affaire de la rue de Lourcin",
        "L’Âge d’Or",
        "L’amant",
        "L’Ambition d’être tendre",
        "L’amour c’est mieux à trois",
        "L’arbre d’Hipollene",
        "L’Arnaqueuse",
        "l’Arrestation",
        "L’Art de Suzanne Brut",
        "L’ascenseur",
        "L’Attrape Dieux",
        "L’Audition",
        "L’Avare",
        "L’Avar",
        "L’écho d’un infini (extrait)",
        "L’Écrivain Public",
        "L’effleure du mal",
        "L’enseignement de l’ignorance",
        "L’épreuve d’amitié",
        "L’Equation",
        "L’Etrange",
        "L’Evadée (Les Petites Histoires ",
        "volume 1)",
        "L’évangile selon Pilate",
        "L’histoire du communisme racon",
        "malades mentaux",
        "L’histoire du sexe pour les femmes -encore ",
        "L’homme canon",
        "L’homme de Schrödinger",
        "L’homme est une comédie dramatique",
        "L’Homme sans souci",
        "L’humanzee",
        "L’île Turbi",
        "L’incroyable histoire des jouets",
        "L’Ingénu",
        "L’introspection du général",
        "L’oeil du cyclone",
        "L’Oeil égaré",
        "L’oiseau migrateur",
    ];

    private $places = [
        "11 • GILGAMESH BELLEVILLE",
        "3 RAISINS",
        "3 SOLEILS (THÉÂTRE / GALERIE)",
        "56 REMPART (THÉÂTRE DU)",
        "95. AU VERBE FOU,THÉÂTRE LITTÉRAIRE",
        "ACTUEL (THÉÂTRE)",
        "ADRESSE (L’)",
        "AJMI Jazz Club - LA MANUTENTION",
        "ALBATROS",
        "ALIBI (L’)",
        "ALIZÉ",
        "AMANTS (THÉÂTRE DES)",
        "AMBIGU THÉÂTRE",
        "ANGE (THÉÂTRE DE L’)",
        "ARCAS",
        "ARCHIPEL THÉÂTRE",
        "ARRACHE-COEUR (THÉÂTRE L’)",
        "ARTÉPHILE",
        "ARTO",
        "ATELIER 44 (L’)",
        "ATELIER FLORENTIN (THÉÂTRE DE L’)",
        "ATYPIK THÉÂTRE",
        "AU BOUT LÀ-BAS (THÉÂTRE)",
        "AU COIN DE LA LUNE",
        "AU MAGASIN",
        "AU VIEUX BALANCIER",
        "AUTRE CARNOT (THÉÂTRE L’)",
        "AVIGNON-REINE BLANCHE",
        "BALCON (THÉÂTRE DU)",
        "BARRETTA (THÉÂTRE)",
        "BARRIQUES (THÉÂTRE DES)",
        "BÉLIERS (THÉÂTRE DES)",
        "BO (THÉÂTRE)",
        "BOURSE DU TRAVAIL CGT(THÉÂTRE DE LA)",
        "BRUNES (THÉÂTRE DES)",
        "BUFFON",
        "CABESTAN (THÉÂTRE LE)",
        "CAPITOLE (EX PANDORA)",
        "CARMES ANDRÉ BENEDETTO(THÉÂTRE DES)",
        "CARNOT (THÉÂTRE)",
        "CARRETERIE (THÉÂTRE DE LA)",
        "CASERNE (LA)",
        "CASTELET (THÉÂTRE LE)",
        "CENTRE (THÉÂTRE DU)",
        "CHAPEAU D’ÉBÈNE THÉÂTRE",
        "CHAPEAU ROUGE THÉÂTRE",
        "CHAPELLE DE L’ORATOIRE",
        "CHAPELLE DU VERBE INCARNÉ",
        "CHÊNE NOIR (THÉÂTRE DU) -Direction Gérard Gelas",
        "CHIEN QUI FUME (THÉÂTRE DU)",
        "CINÉVOX THÉÂTRE (LE)",
        "CLASH THÉÂTRE",
        "COLLÈGE DE LA SALLE",
        "CONDITION DES SOIES",
        "CORPS SAINTS (THÉÂTRE DES)",
        "CROISÉE DES CHEMINSAVIGNON (LA)",
        "DOMS (THÉÂTRE DES)",
        "ÉCOLE DU SPECTATEUR",
        "ENTREPÔT (L’) - Cie Mises en Scène",
        "ÉPISCÈNE (THÉÂTRE )",
        "ESPACE ALYA",
        "ESPACE ROSEAU TEINTURIERS",
        "ESPACE SAINT MARTIAL",
        "ESSAÏON-AVIGNON",
        "ÉTINCELLE (THÉÂTRE DE L’)",
        "FABRIK THÉÂTRE",
        "FACTORY (LA) - Salle Tomasi",
        "FACTORY (LA) - Théâtre de l’Oulle",
        "FORUM (LE)",
        "GARAGE INTERNATIONAL (THE)",
        "GÉMEAUX (THÉÂTRE DES)",
        "GIRASOLE (THÉÂTRE DU)",
        "GOLOVINE (THÉÂTRE)",
        "GRAND PAVOIS (THÉÂTRE LE)",
        "GRAND PETIT THÉÂTRE (LE)",
        "HALLES (THÉÂTRE DES)",
        "HAUTS PLATEAUX (LES)(La Manutention)",
        "HIVERNALES (LES) - CDCNd’Avignon",
        "HUMANUM 149",
        "LOT CHAPITEAUX",
        "IMPROVIDENCE (THÉÂTRE)",
        "ISLE 80",
        "ITALIENS ((THÉÂTRE DES)",
        "KABAROUF BARTHELASSE",
        "LÀ ! C’EST DE LA MUSIQUE(CONCERTS)",
        "LASCIERIE",
        "LAURETTE THÉÂTRE AVIGNON",
        "LILA’S (THÉÂTRE DES)",
        "LUCIOLES (THÉÂTRE DES)",
        "LUNA (THÉÂTRE LA)",
        "MAISON DE LA PAROLE",
        "MAISON DE LA POÉSIED’AVIGNON",
        "MAISON DU THÉÂTREPOUR ENFANTS",
        "MANUFACTURE (LA)",
        "NOTRE DAME (THÉÂTRE)",
        "OBSERVANCE (THEATRE DE L’)",
        "OCCITANIE FAIT SON CIRQUE ENAVIGNON",
        "OPTIMIST (THÉÂTRE L’)",
        "PALACE (THÉÂTRE LE)",
        "PARADISE RÉPUBLIQUE",
        "PARENTHÈSE (LA)",
        "PARIS (LE)",
        "PARVIS D’AVIGNON (LE)",
        "PETIT CHIEN (THÉÂTRE LE)",
        "PETIT LOUVRE (TEMPLIERS)",
        "PETIT LOUVRE (VAN GOGH)",
        "PETITE CASERNE (LA)",
        "PIXEL AVIGNON",
        "PIXEL AVIGNON SALLE BAYAF",
        "PORTE SAINT MICHEL(THÉÂTRE DE LA)",
        "PRÉSENCE PASTEUR",
        "ROI RENÉ (THÉÂTRE DU)",
        "ROTONDE (THÉÂTRE DE LA)",
        "ROUGE GORGE",
        "SALLE ROQUILLE",
        "SHAM’S",
        "TACHE D’ENCRE (THÉÂTRE DE LA)",
        "TRAIN BLEU (THÉÂTRE DU)",
        "TRANSVERSAL (THÉÂTRE)",
        "TREMPLIN - Salle Les Baladins",
        "TREMPLIN - Salle Molière",
        "CONTRE COURANT (FESTIVAL)",
        "PETITES FORMES (MONTFAVET -FESTIVAL LES)",
        "VILLENEUVE EN SCÈNE(FESTIVAL)",
    ];

    private $adresses = [
        "11, boulevard Raspail",
        "15, rue Thiers",
        "4, rue Buffon",
        "56, rue du rempart Saint Lazare",
        "95, rue des infirmières",
        "2, avenue de la Trillade",
        "4, rue des Escaliers Sainte-Anne",
        "29, rue des Teinturiers",
        "27, rue des Teinturiers",
        "15, rue du 58e R.I",
        "1, place du Grand Paradis",
        "7, rue de la Bourse",
        "15-17, rue des Teinturiers",
        "147, allée Antoine Pinay",
        "25 bis, rue du Rempart de l’Oulle",
        "13, rue du 58e R.I - Porte Limbert",
        "5 bis, rue Bourg Neuf",
        "3, rue Râteau",
        "44, rue Thiers",
        "28, rue Guillaume Puy",
        "95, rue de la Bonneterie",
        "23, rue Noël Biret",
        "24, rue Buffon",
        "31, rue des Teinturiers",
        "2, rue d’Amphoux",
        "7, rue Carnot",
        "16, rue de la Grande Fusterie",
        "38, rue Guillaume Puy",
        "12, place Saint Didier",
        "8, rue Ledru Rollin",
        "53, rue du Portail Magnanen",
        "Rue Campane",
        "32, rue Thiers",
        "18, rue Buffon",
        "11, rue du Collège de la Croix",
        "3, rue Pourquery Boisserin",
        "6, place des Carmes",
        "16, rue Carnot",
        "116, rue de la Carreterie",
        "113, rue de la Carreterie",
        "13, rue Louis Pasteur",
        "13, rue de la velouterie",
        "34-36, rue du Chapeau Rouge",
        "32, rue Joseph Vernet",
        "21G, rue des Lices",
        "8 bis, rue Sainte Catherine",
        "75, rue des Teinturiers",
        "22, place de l’Horloge",
        "3, place Pasteur",
        "13, rue de la Croix",
        "76, place des Corps Saints",
        "25, rue d’Amphoux",
        "1 bis, rue des Escaliers Ste-Anne",
        "5, Place Louis Gastin",
        "1 ter, boulevard Champfleury",
        "5 , rue Ninon Vallin",
        "31 bis, rue Guillaume Puy",
        "45, rue des Teinturiers",
        "2, rue Henri-Fabre",
        "33, rue de la Carreterie",
        "14, place des Études",
        "4, rue Bertrand",
        "19, place Crillon",
        "rue de la Balance",
        "24 bis, rue Guillaume Puy",
        "1 bis, rue Sainte-Catherine",
        "13, rue Bouquerie",
        "Rue du Roi René",
        "4, rue des Escaliers Sainte Anne",
        "18, rue Guillaume Puy",
        "149, rue Carreterie",
        "353, chemin des Canotiers,",
        "Île de la Barthelasse",
        "63, rue Guillaume Puy",
        "18, place des Trois Pilats",
        "82 bis, rempart Saint Lazare",
        "Chemin des Canotiers",
        "Île de la Barthelasse",
        "34, rue Joseph Vernet",
        "15, boulevard du Quai Saint Lazare",
        "14, rue Plaisance",
        "16/18, rue Joseph Vernet",
        "1, rue Séverine",
        "7, rue du Prévot",
        "6, rue Figuière",
        "2 bis, rue des Écoles",
        "13 à 17, rue du Collège d’Annecy",
        "22, chemin de l’Île Piot",
        "38, cours Jean Jaurès",
        "9, rue Mignard",
        "18, rue des Études",
        "5, rue Henri Fabre",
        "33, rue Paul Saïn",
        "76, rue Guillaume Puy",
        "3, rue Felix Gras",
        "23, rue Saint Agricol",
        "119, rue Carreterie",
        "18, rue Guillaume Puy",
        "23, rue Saint Michel",
        "13, rue du Pont Trouca",
        "4 bis, rue Grivolas",
        "1A, rue Jean Catelas",
        "Place de l’Amirande",
        "3, rue Roquille",
        "25, rue Saint Jean Le Vieux",
        "1, rue de la Tarasque",
        "Salle Les Baladins H",
        "7, rue du Bon Pasteur",
        "8 ter, rue Cornue",
        "Île de la Barthelasse",
        "Plaine de l’Abbaye",
        "2, rue Portail Mathéron",
        "1, chemin de l’Île Piot – Sous le",
        "pont Daladier",
        "de la Barbière PLAN 2 N",
        "23 bis, rue Thiers",
        "15, rue Louis Pasteur",
        "pont d’Avignon E",
        "2, rue Ferruce",
        "17, rue Petite Fusterie",
        "17, rue Portail Matheron",
        "2, rue Mignard",
        "6 ,rue de l’Olivier",
        "2 bis, rue Laboureur",
        "15, rue Portail Matheron",
        "17, rue Victor Hugo",
        "157, rue des Écoles",
    ];

    private $troops = [
        "...keep dreaming",
        "6’Thèmes Théâtre (Compagnie Le)",
        "Accord Parfait (Compagnie)",
        "Ad Libitum (Compagnie)",
        "Affamés (Compagnie Les)",
        "Alain Bertrand (Compagnie)",
        "Aller-Retour Théâtre (Compagnie)",
        "Apart (Compagnie)",
        "ARAP Association Centre culturel",
        "Art’Maniac Théâtre (Compagnie)",
        "Artiflette (Compagnie)",
        "Artist prod",
        "Artist’ Prod",
        "Artscène (Cie)",
        "Asphodèles (Compagnie des)",
        "Atypik Production-Diffusion / Compagnie La",
        "Jacp",
        "Auditorium Seynod Scène Régionale Aura /",
        "Cie Choses Dites",
        "Aussi... Mais pas que ! (Compagnie)",
        "Bacchanales Productions",
        "Beaver Dam (Compagnie)",
        "Bonlieu Scène Nationale / Cie Dont",
        "Acte",
        "Borda (Compagnie)",
        "Carton Compagnie",
        "Cause Toujours (Cie)",
        "Chansons de gestes (Compagnie)",
        "Choses Dites (Cie)",
        "Cie Courir à la Catastrophe",
        "Collectif GRIM(M) / Cie Ithéré",
        "Collectif X",
        "Collectif Yggdrasil / Compagnie Nandi",
        "Compagnie des prairies / Manufacture",
        "(la)",
        "Contrepoint (Compagnie)",
        "Coopérative Citoyenne (Compagnie de",
        "la)",
        "Crazy et Salon Marengo (Compagnie)",
        "359",
        "Croc’scène",
        "De Là (Cie)",
        "Dissedere (Cie)",
        "Dont Acte (Cie)",
        "Du Bord de l’eau (Cie)",
        "Dychka (Compagnie)",
        "Elégie (Compagnie)",
        "En Acte(S) (Compagnie)",
        "En aparté théâtre (Compagnie)",
        "En Scène et ailleurs (Compagnie)",
        "Ensemble Agora",
        "Entracteprod / Association",
        "aviscene",
        "Evedia",
        "Flic-Floc (Compagnie)",
        "Florent Hermet",
        "Fox Compagnie (Compagnie)",
        "Futilité Publique (Cie)",
        "Grand Courbe (Compagnie Le)",
        "Gregory Cometti Productions",
        "Haut les mains (Compagnie)",
        "Homard Bleu (Compagnie Le)",
        "Horizon Live",
        "Humanum 149 / Compagnie Les",
        "Hublots",
        "Idéale (Compagnie)",
        "Il Suffirait de Presque Rien (Compagnie)",
        "Improvidence",
        "Improvidence / Again! Productions",
        "Jean-Claude Gallotta (Cie)",
        "Jet d’Encre (Compagnie du)",
        "JimOe (Cie)",
        "L’Envolante Théâtre et sons",
        "(Compagnie)",
        "L’Espace Gerson",
        "L’étoile et les fils (Compagnie)",
        "La Fédération - cie Philippe Delaigue",
        "La Gueule Ouverte (Compagnie)",
        "La langue des oiseaux (Cie)",
        "La Lune à l’Envers (Compagnie)",
        "La Pendue (Compagnie)",
        "La Trèshorrificque Compagnie",
        "Lardenois et Cie",
        "Le Centre imaginaire",
        "Le Complexe Production",
        "Le Grand Angle à Voiron, Le Théâtre du",
        "Vellein à Villefontaine / Lardenois et",
        "Cie",
        "Le Grand Nulle Part / Compagnie En",
        "Acte(S)",
        "Le KFT / ...keep dreaming",
        "Le KFT / Compagnie ACTA",
        "Le Neil (Compagnie)",
        "Le Souffleur de Verre (Compagnie)",
        "Le Théâtre Oblique (Cie)",
        "Les Indiens (Compagnie)",
        "Les Nouveaux Nez & Cie",
        "Les Vertébrées / Compagnie L’étoile et les",
        "fils",
        "Malka (Compagnie)",
        "Marconnet Diffusion",
        "Matcha",
        "Mégalops (Compagnie Les)",
        "Minotaure (Compagnie Le)",
        "Mix’arts (Compagnie)",
        "Nandi (Compagnie)",
        "Nuevo Mundo",
        "Oatsquad (Cie)",
        "Odyssée ensemble & cie",
        "Parvenus (Compagnie Les)",
        "Passeurs de mémoires",
        "Peut-être... (Compagnie)",
        "Premier Acte (Cie)",
        "Prévert, Piano & Poésie",
        "Prisma Teatro (Compagnie)",
        "Rê-Volt (Cie)",
        "Serge Paumier Production",
        "Serge Paumier Prodution / Plateforme",
        "Diffusion",
        "Serra Bernhardt (Compagnie)",
        "Tagadatsing (Cie)",
        "Teatro Golondrino",
        "Thalie (Compagnie)",
        "Théâtre barretta / Coq Héron",
        "Productions",
        "Théâtre Comédie Odéon",
        "Théâtre de Romette",
        "Théâtre des ilets - CDN / Compagnie",
        "Travelling Théâtre",
        "Théâtre des Pénitents / Compagnie Travelling",
        "Théâtre",
        "Théâtre du Parc / Théâtres Entre Deux",
        "Théâtre Le Balcon / ki m’aime me",
        "suive",
        "Théâtre Le Palace / Compagnie Dychka",
        "Théâtre Libre (Compagnie)",
        "Théâtre Remue-Méninges (Compagnie)",
        "Théâtres Entre Deux",
        "Théâtres Entre-Deux",
        "Théorème de Planck (Compagnie)",
        "TJM Saint-Fons / Compagnie Le Voyageur",
        "Debout",
        "Tonic Agency (Cie)",
        "Tony DI",
        "Travelling Théâtre (Compagnie)",
        "Tréteaux 4 Vents",
        "Uzinason",
        "Vitriers Lunatiques (Compagnie Les)",
        "Volodia Théâtre (Compagnie)",
        "Volubile (Compagnie La)",
        "Voyageur Debout (Compagnie Le)",
        "Yes High Tech",
        "ZAD (Zone Artistique à Défendre)",
        "(Compagnie)",
        "Zoro Zora / Les Inédits (Cie)",
        "“Ponctuation !” (Compagnie)",
        "Bacchus (Compagnie)",
        "Barbès 35 (Compagnie)",
        "Christelle Loury",
        "Compagnie de la lionne / Cie Le bouc sur le",
        "toit",
        "Conte en chemin (Compagnie)",
        "day-for-night/Anne Monfort (Cie)",
        "Du Détour (Compagnie)",
        "El Ajouad (Compagnie)",
        "Entrescenes / Robin Production",
        "f.o.u.i.c",
        "Festival de caves / Cie Day-for-night/Anne",
        "Monfort",
        "GBEC (Compagnie)",
        "Guillaume pierre (Cie)",
        "Hums - Dijon/La Réunion (Compagnie)",
        "Illusion ou Realité (Compagnie)",
        "La Servante (Compagnie)",
        "Le Théâtre, Scène conventionnée d’Auxerre /",
        "Compagnie Barbès 35",
        "Les amis de madame Ruffiaud",
        "(Compagnie)",
        "Les Créations Manta",
        "Les Enfants Phares (Compagnie)",
        "Parfum de scènes (Compagnie)",
        "Pocket Théâtre",
        "Ring-Théâtre (Compagnie Le)",
        "Rue des Chimères (Compagnie)",
        "Taxi-Brousse (Cie)",
        "Théâtre de l’Accalmie (Cie)",
        "Théâtre de l’Espoir (Compagnie)",
        "Théâtre de l’espoir / Compagnie Les airs",
        "entendus",
        "Théâtre Edwige Feuillère Vesoul / Cie Les",
        "Epis Noirs",
        "Théâtre Nomade (Compagnie du)",
        "Un Jour J’irai (Compagnie)",
        "Youz (Cie)",
        "Youz / Compagnie Les Enfants Phares",
        "2052 (Compagnie)",
        "709 Prod / Emile et une nuit Prod",
        "Aller Retour Compagnie",
        "Aller Retour Compagnie / Aller Retour",
        "Compagnie",
        "Cambrioleurs (Compagnie Les)",
        "Centre Chorégraphique National de Rennes et",
        "de Bretagne",
        "Chiens de paille (Compagnie Les)",
        "Collectif Aïe Aïe Aïe",
        "CPPC Théâtre de L’Aire Libre / Espace 110 /",
        "Munstrum Théâtre",
        "Écume&Acide / Compagnie Les",
        "Entichés",
        "Festival du Lyncéus / Cie Choses Dites",
        "Ile Lauma (Compagnie de l’)",
        "Juglair",
        "La Belle Idée (Compagnie)",
        "Le groupe vertigo",
        "Living en Mars",
        "Nevez Productions (Cie)",
        "Propagande C (Cie)",
        "Zabraka (Compagnie)",
        "Antilope (Compagnie)",
        "Cartel (Compagnie)",
        "Casab’art (Compagnie)",
        "Cavalcade (Cie)",
        "Chat Pitre (Compagnie)",
        "Cheyenne Productions",
        "Cie Not’ Compagnie",
        "Filipe Lourenço (Compagnie)",
        "Grand Théâtre (Compagnie)",
        "Hécate (Compagnie)",
        "Hiro Productions et Smile Conseils",
        "Intime Compagnie",
        "L’arsène production",
        "L’Échalier / Compagnie Les Entichés",
        "L’Echappée Belle (Compagnie)",
        "L’Idée du Nord",
        "La Famille Morallès",
        "La Tite (Compagnie)",
        "Léla (Compagnie)",
        "Les Entichés (Compagnie)",
        "Lili Böm (Compagnie)",
        "Maison de la Culture de Bourges - Scène",
        "nationale / Compagnie Les Entichés",
        "Marjolaine Karlin",
        "Mind The Gap",
        "Mireille (Compagnie)",
        "Not’ Compagnie (Cie)",
        "Objectif 300",
        "Oeil brun (Cie)",
        "Originavre (Compagnie)",
        "Roseau Théâtre Originavre",
        "Sept-Epées (Compagnie)",
        "Théâtre à cru",
        "Théâtre Dans la Nuit (Compagnie)",
        "Théâtre de Chartres / Compagnie Lili",
        "Böm",
        "Theatre de l’Imprévu / Passeurs de",
        "mémoires",
        "A Scintilla Balanina (Cie)",
        "Ecl’adam (Compagnie)",
        "La Compagnie Spirale",
        "Productions du Théâtre du Partage",
        "(Compagnie Les)",
        "Théâtre du partage",
        "Accès-Soir (Compagnie)",
        "Astrov (Compagnie)",
        "Atelier du Premier Acte",
        "Bizet & Co (Compagnie)",
        "Centre dramatique national la Manufacture /",
        "Compagnie Le Plateau Ivre",
        "Claire Sergent (Compagnie)",
        "Compagnie Astrov",
        "Corpus Urbain (Compagnie Le)",
        "DH Management (Compagnie)",
        "Du sapin sur la planche (Compagnie)",
        "Histoire d’eux (Compagnie)",
        "In Vitro / Marine Mane (Cie)",
        "Indigo théâtre (Compagnie)",
        "Itek (Compagnie)",
        "Kiai (Compagnie)",
        "La bande passante (Cie)",
        "La Comédie, CDN de Reims / Compagnie Le",
        "Corpus Urbain",
        "La Compagnie Théâtr’âme / Compagnie Le",
        "Corpus Urbain",
        "La Filature / Compagnie Papierthéâtre",
        "La Mâchoire 36 (Compagnie)",
        "La Manufacture-Centre Dramatique National",
        "Nancy Lorraine / Châteauvallon-Scène",
        "nationale",
        "Le Plateau Ivre (Compagnie)",
        "Le Talon Rouge (Cie)",
        "Munstrum Théâtre",
        "Nest-CDN transfrontalier de Thionville-Grand",
        "One Woman Show",
        "Onom (Compagnie)",
        "Papierthéâtre (Compagnie)",
        "Premiers Actes (Cie)",
        "Scènes Vosges / Compagnie Le Plateau",
        "Ivre",
        "SN de Mulhouse / Munstrum Théâtre",
        "Swing ! (Compagnie)",
        "Théâtre Des Bonnes Langues",
        "(Compagnie)",
        "Théâtre en Scène (Compagnie)",
        "Ultima Necat",
        "20h40 Productions",
        "À vrai dire (Compagnie)",
        "Atelier de la Nonette",
        "Avec vue sur la mer (Compagnie)",
        "Barbooza (Compagnie)",
        "BordCadre (Cie)",
        "Catalyst (Compagnie)",
        "cie des mers du Nord / Scène & Public",
        "Collectif Bette Davis",
        "Collectif c’est quand bientôt ?",
        "Comédie de Picardie / Compagnie À vrai",
        "dire",
        "Comédie de Picardie / Compagnie Les",
        "Indiens",
        "Compagnie Etrange Ete / Collectif Bette",
        "Davis",
        "Compagnie L’Échappée",
        "Dans l’arbre (Compagnie)",
        "Des Fourmis dans la Lanterne (Cie)",
        "Dreamdust Production",
        "Embellie Cie (L’)",
        "Espace Jean Legendre - Théâtre de",
        "Compiègne / Compagnie Teatro di",
        "Fabio",
        "Franchement, tu (Cie)",
        "Grand Boucan (Cie)",
        "H3P (Compagnie)",
        "Hauts-de-France Productions",
        "Hilaretto (Compagnie)",
    ];

    private $email = [
        "@gmail.com",
        "@outlook.fr",
        "@hotmail.fr",
        "@caramail.com",
    ];

    private $image = [
        "default.png",
        "aceuxqui.png",
        "antioche.png",
        "burnout.png",
        "dubruitetdelafureur.jpg",
        "hamlet.jpg",
        "lacolombine.png",
        "ladouceur.png",
        "le_petit_boucher_avignon_cie_edlf-1.png",
        "les-prc3a9cieuses-ridicules-thc3a9c3a2tre-des-barriques-festival-avignon-2015-affiche.jpg",
        "mecanique_du_hasard-1.png",
        "precious-ridiculous-affiche-festival-avignon-off-2014.jpg"
    ];

    private $time = [
        "10:00",
        "10:30",
        "11:00",
        "11:30",
        "12:00",
        "12:30",
        "13:00",
        "13:30",
        "14:00",
        "14:30",
        "15:00",
        "15:30",
        "16:00",
        "16:30",
        "17:00",
        "17:30",
        "18:00",
        "18:30",
        "19:00",
        "19:30",
        "20:00",
        "20:30",
        "21:00",
        "21:30",
        "22:00"
    ];

    /**
     * return one random style
     */
    public function eventStyle()
    {
        return $this->styles[array_rand($this->styles)];
    }

    /**
     * return one random title
     */
    public function eventTitle()
    {
        return $this->titles[array_rand($this->titles)];
    }

    /**
     * return one random place
     */
    public function eventPlace()
    {
        return $this->places[array_rand($this->places)];
    }

    /**
     * return one random adress
     */
    public function eventAdress()
    {
        return $this->adresses[array_rand($this->adresses)];
    }

    /**
     * return one random troop name
     */
    public function eventTroop()
    {
        return $this->troops[array_rand($this->troops)];
    }

    /**
     * return one random email provider
     */
    public function userEmail()
    {
        return $this->email[array_rand($this->email)];
    }

        /**
     * return one random image
     */
    public function imageRand()
    {
        return $this->image[array_rand($this->image)];
    }

            /**
     * return one random time
     */
    public function timeRand()
    {
        return $this->time[array_rand($this->time)];
    }
}
